# name: Firebase Continuous Deployment

# on: push

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout branch
#         uses: actions/checkout@v1

#       - name: Use Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12.16

#       - name: Install dependencies
#         run: npm install

#       - name: Build & deploy
#         run: npm run deploy
#         env:
#           CI: true
#           FIREBASE_TOKEN: ${{ secrets.YOUR_SECRET }}
